name: Endform
on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm i -g endform && npm install -g pnpm && pnpm install

      - name: Run tests with Endform
        run: npx endform test
        env:
          ENDFORM_API_KEY: ${{ secrets.ENDFORM_API_KEY }}
