name: Playwright Tests - sharded on 10 machines
on:
  workflow_dispatch:

jobs:
  test:
    uses: endformdev/demo-pw-test-suite/.github/workflows/playwright-x-shards.yml@main
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        shardTotal: [10]
    with:
      shardIndex: ${{ matrix.shardIndex }}
      shardTotal: ${{ matrix.shardTotal }}
