name: Playwright Tests - sharded on 25 machines
on:
  workflow_dispatch:

jobs:
  test:
    uses: endformdev/demo-pw-test-suite/.github/workflows/playwright-x-shards.yml@main
    strategy:
      fail-fast: false
      matrix:
        shardIndex:
          [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
          ]
        shardTotal: [25]
    with:
      shardIndex: ${{ matrix.shardIndex }}
      shardTotal: ${{ matrix.shardTotal }}
