name: Playwright Tests - sharded on 2 machines
on:
  workflow_dispatch:

jobs:
  test:
    uses: endformdev/demo-pw-test-suite/.github/workflows/playwright-x-shards.yml@main
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
    with:
      shardIndex: ${{ matrix.shardIndex }}
      shardTotal: ${{ matrix.shardTotal }}
