name: Playwright Tests - sharded on 1 machine
on:
  workflow_dispatch:

jobs:
  test:
    uses: endformdev/demo-pw-test-suite/.github/workflows/playwright-x-shards.yml@main
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1]
        shardTotal: [1]
    with:
      shardIndex: ${{ matrix.shardIndex }}
      shardTotal: ${{ matrix.shardTotal }}

  merge-reports:
    # Merge reports after playwright-tests, even if some shards have failed
    if: ${{ !cancelled() }}
    needs: [test]
    uses: endformdev/demo-pw-test-suite/.github/workflows/playwright-html-report.yml@main
